project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "projects/**/*.qmd"
    - "!projects/**/notebooks/"

website:
  title: "Elaine Patrao"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

    right:
      - icon: github
        href: https://github.com/elainepatrao
        aria-label: GitHub

      - icon: linkedin
        href: https://www.linkedin.com/in/elaine-patrao
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    toc: true    